#!/usr/bin/env bash
# Copyright 2026 Duatic AG
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions, and
#    the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions, and
#    the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or
#    promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Derive the release set and the rosdep mapping from what is in src/.
# Generated rather than hand-maintained: the Debian names embed the ROS distro.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# A package is built for a (ROS distro, Ubuntu release) pair. CI builds the matrix.
DISTRO="${ROS_DISTRO_TARGET:-jazzy}"
OS_VERSION="${OS_VERSION:-noble}"

EXCLUDE="${EXCLUDE:-$HERE/exclude.txt}"

python3 - "$HERE" "$DISTRO" "$OS_VERSION" "$EXCLUDE" <<'PY'
import sys, pathlib, xml.etree.ElementTree as ET
here, distro, os_version, exclude_file = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]

# Not released, and why, in exclude.txt rather than in this script: the reason belongs next to the
# name, and a package in a repository Duatic does not own cannot be annotated any other way.
excluded = {}
ep = pathlib.Path(exclude_file)
if ep.is_file():
    for line in ep.read_text().splitlines():
        line = line.split('#', 1)[0].strip()
        if not line: continue
        name, _, reason = line.partition(' ')
        excluded[name] = reason.strip()

# Where a package is served from is declared by the package, in package.xml:
#
#   <export><duatic_archive_root>products/my-product</duatic_archive_root></export>
#
# Not inferred from whether its repository is public. Those are different things: a public
# repository can hold a licensed product. A package that declares nothing lands in "unrouted",
# which no licence grants, so forgetting the field withholds a package rather than publishing it.
DEFAULT_ROOT = 'unrouted'

found = {}
for px in sorted((pathlib.Path(here) / 'src').rglob('package.xml')):
    if '.git' in px.parts: continue
    try: root = ET.parse(px).getroot()
    except Exception: continue
    n = (root.findtext('name') or '').strip()
    if not n or n in excluded: continue
    dest = (root.findtext('export/duatic_archive_root') or '').strip() or DEFAULT_ROOT
    found[n] = dest

names = sorted(found)
(pathlib.Path(here) / 'packages.txt').write_text('\n'.join(names) + '\n')

def deb(n): return f"ros-{distro}-" + n.replace('_', '-')

lines = [f"# ROS package name -> Debian package name, for the Duatic release set.",
         f"# Generated by gen_release_set.sh for {distro} on ubuntu {os_version}.",
         f"# One file per ROS distro: the Debian names embed the distro.",
         f"# {len(names)} packages."]
for n in names:
    lines += [f"{n}:", "  ubuntu:", f"    {os_version}: [{deb(n)}]"]
out = pathlib.Path(here).parent / 'archive' / 'rosdep' / f'rosdep-{distro}.yaml'
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines) + '\n')

# One list per archive root, which is what the publisher iterates. Per distro too, so a rebuild
# for kilted does not un-publish jazzy.
lists = pathlib.Path(here).parent / 'archive' / 'lists'
lists.mkdir(parents=True, exist_ok=True)
for stale in lists.glob(f'*-{distro}.txt'): stale.unlink()
by_root = {}
for n in names: by_root.setdefault(found[n], []).append(n)
for root in sorted(by_root):
    f = lists / f"{root.replace('/', '-')}-{distro}.txt"
    # The root is declared in the file, not encoded in its name: a name cannot say which dash
    # was a slash, and products/product-a would decode to products/product/a.
    body = '\n'.join(deb(n) for n in sorted(by_root[root]))
    f.write_text(f'# root: {root}\n{body}\n')

print(f"  {len(names)} packages for {distro}/{os_version} -> packages.txt")
if excluded:
    print(f"  {len(excluded)} excluded by {ep.name}")
print(f"  mapping -> {out}")
for root in sorted(by_root):
    print(f"  {root:<24} {len(by_root[root]):>3} packages")
if DEFAULT_ROOT in by_root:
    print(f"  WARNING: {len(by_root[DEFAULT_ROOT])} packages declare no <duatic_archive_root>:")
    for n in sorted(by_root[DEFAULT_ROOT]): print(f"    {n}")
PY
