// Header generated by duatic_helper_msgs: this will not compile unless that dependency was
// resolved and installed from apt.
#include <duatic_helper_msgs/srv/attach_model.hpp>

namespace duatic_probe
{

bool has_explicit_holder(const duatic_helper_msgs::srv::AttachModel::Request& request)
{
  return !request.parent_model.empty();
}

}  // namespace duatic_probe
