#!/usr/bin/env bash
# Copyright 2026 Duatic AG
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions, and
#    the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions, and
#    the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or
#    promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Publish one signed archive root per licensable unit. Runs INSIDE a container; see README.
#
# One root per licence rather than components in one archive: a gated component makes apt fetch
# an InRelease advertising paths it then 403s on, reported as a broken repository.
#
# Usage (inside container):  /work/publish_archives.sh [stamp]

set -euo pipefail

WORK=/work                      # this directory
DIST="${DIST:-/dist}"           # published trees, visible on the host
PKGDIRS="${PKGDIRS:-/out /builder-out}"
GPGDIR="${GPGDIR:-$WORK/gnupg}"
APTLYDIR="${APTLYDIR:-$WORK/aptly}"
CONF=/tmp/aptly.conf
STAMP="${1:-$(date +%Y%m%d%H%M%S)}"

HOST_UID="${HOST_UID:-0}"; HOST_GID="${HOST_GID:-0}"
hand_back() { [ "$HOST_UID" = "0" ] && return 0
    chown -R "$HOST_UID:$HOST_GID" "$DIST" "$GPGDIR" "$APTLYDIR" 2>/dev/null || true; }
trap hand_back EXIT

# Generated by workspace/gen_release_set.sh. The Ubuntu release decides the suite; the ROS distro
# is already in the package name, so one suite carries every ROS distro built for that Ubuntu.
OS_VERSION="${OS_VERSION:-noble}"
CHANNEL="${CHANNEL:-nightly}"
SUITE="${OS_VERSION}-${CHANNEL}"
LISTS="${LISTS:-$WORK/lists}"

# One archive root per list, generated by workspace/gen_release_set.sh from the
# <duatic_archive_root> each package declares. A root named "unrouted" is not published: it holds
# packages that declared nothing, and publishing them would guess at who may fetch them.
[ -d "$LISTS" ] || { echo "FATAL: no package lists at $LISTS. Run gen_release_set.sh first." >&2; exit 1; }

declare -A ROOT_SET=()
for f in "$LISTS"/*.txt; do
    [ -f "$f" ] || continue
    root="$(sed -n 's/^# root: //p' "$f" | head -1)"
    [ -n "$root" ] || { echo "FATAL: $f declares no root" >&2; exit 1; }
    if [ "$root" = "unrouted" ]; then
        echo "--- skipping $(grep -cv '^#' "$f") unrouted packages"; continue
    fi
    ROOT_SET["$root"]="${ROOT_SET[$root]:-} $(grep -v '^#' "$f" | tr '\n' ' ')"
done
[ ${#ROOT_SET[@]} -gt 0 ] || { echo "FATAL: every package is unrouted; nothing to publish." >&2; exit 1; }

echo "--- publishing suite $SUITE"

# endpoint | published tree | package names it holds
ARCHIVES=()
for root in $(printf '%s\n' "${!ROOT_SET[@]}" | sort); do
    case "$root" in
        public) tree="$DIST/public" ;;
        *)      tree="$DIST/private/$root" ;;
    esac
    ARCHIVES+=("$root|$tree|${ROOT_SET[$root]}")
    echo "    $root -> $tree"
done

echo "--- installing aptly and gnupg"
apt-get update -qq
apt-get install -y -qq --no-install-recommends aptly gnupg jq

# ---------------------------------------------------------------- signing key
export GNUPGHOME="$GPGDIR"
mkdir -p "$GNUPGHOME"; chmod 700 "$GNUPGHOME"
# Generating a key is opt-in. Robots pin this key with Signed-By, so a new one breaks apt on every
# robot, and the replacement keyring cannot ship through the archive it broke.
if ! gpg --list-secret-keys --with-colons 2>/dev/null | grep -q '^sec'; then
    [ "${ALLOW_THROWAWAY_KEY:-0}" = "1" ] || {
        echo "FATAL: no signing key in $GPGDIR." >&2
        echo "  Production: restore the archive key. A new key is not a recovery step." >&2
        echo "  Local: re-run with ALLOW_THROWAWAY_KEY=1 to generate one." >&2
        exit 1
    }
    echo "--- generating a throwaway signing key"
    # RSA: universally verifiable by apt clients, and this key must outlive the fleet.
    gpg --batch --gen-key <<EOF
%no-protection
Key-Type: RSA
Key-Length: 4096
Key-Usage: sign
Name-Real: ${KEY_NAME:-Archive Signing Key}
Name-Email: ${KEY_EMAIL:-apt@example.invalid}
Expire-Date: 0
%commit
EOF
fi
KEYID="$(gpg --list-secret-keys --with-colons | awk -F: '/^fpr/{print $10; exit}')"
[ -n "$KEYID" ] || { echo "FATAL: no signing key" >&2; exit 1; }

# Required wherever robots trust the archive: signing with the wrong key produces an archive they
# reject, and finding out here is cheaper than finding out per robot. Only the throwaway key, which
# nothing trusts, may publish without it.
if [ -z "${EXPECTED_KEY_FPR:-}" ]; then
    [ "${ALLOW_THROWAWAY_KEY:-0}" = "1" ] || {
        echo "FATAL: EXPECTED_KEY_FPR is not set." >&2
        echo "  Production: set it to the fingerprint robots pin." >&2
        echo "  Local: re-run with ALLOW_THROWAWAY_KEY=1." >&2
        exit 1
    }
elif [ "$KEYID" != "$EXPECTED_KEY_FPR" ]; then
    echo "FATAL: signing key is $KEYID, expected $EXPECTED_KEY_FPR" >&2
    exit 1
fi
mkdir -p "$DIST"
# Written via a temporary: the redirect truncates before gpg runs, and this path must stay
# fetchable at all times.
gpg --export "$KEYID" > "$DIST/.duatic-archive.gpg.tmp"
[ -s "$DIST/.duatic-archive.gpg.tmp" ] || { echo "FATAL: exported keyring is empty" >&2; exit 1; }
mv "$DIST/.duatic-archive.gpg.tmp" "$DIST/duatic-archive.gpg"
echo "    key $KEYID"

# ---------------------------------------------------------------- aptly config
mkdir -p "$APTLYDIR"
# jq rather than printf: generated JSON that cannot be malformed needs no validity check.
endpoints='{}'
for entry in "${ARCHIVES[@]}"; do
    ep="${entry%%|*}"; rest="${entry#*|}"; tree="${rest%%|*}"
    mkdir -p "$tree"
    endpoints="$(printf '%s' "$endpoints" \
        | jq --arg e "$ep" --arg r "$tree" '.[$e] = {rootDir: $r, linkMethod: "copy"}')"
done
jq -n --arg root "$APTLYDIR" --argjson eps "$endpoints" \
    '{rootDir: $root, FileSystemPublishEndpoints: $eps}' > "$CONF"

apt_ly() { aptly -config="$CONF" "$@"; }
# sed, not grep: grep exits 1 on no match, which under pipefail fails the whole pipeline.
norm() { tr -d ' ' | tr ',' '\n' | sed '/^$/d' | sort -u | paste -sd, -; }

# ---------------------------------------------------------------- publish each root
for entry in "${ARCHIVES[@]}"; do
    ep="${entry%%|*}"; rest="${entry#*|}"; tree="${rest%%|*}"; prefixes="${rest#*|}"

    echo
    echo "=============================================================="
    echo " $ep  ->  ${tree#$DIST/}"
    echo "=============================================================="

    repo="${ep}-${OS_VERSION}"
    apt_ly repo show "$repo" >/dev/null 2>&1 \
        || apt_ly repo create -distribution="$OS_VERSION" -component=main "$repo" >/dev/null

    shopt -s nullglob
    found=()
    for dir in $PKGDIRS; do
        for pfx in $prefixes; do
            for f in "$dir/${pfx}"_*.deb "$dir/${pfx}"-dbgsym_*.ddeb; do found+=("$f"); done
        done
    done
    shopt -u nullglob

    if [ ${#found[@]} -eq 0 ]; then
        echo "    !! no packages matching [$prefixes] in $PKGDIRS - skipping"
        continue
    fi
    for f in "${found[@]}"; do
        echo "    + $(basename "$f")"
        # -force-replace: a rebuild of the same version has different bytes and aptly refuses it.
        # Never on a published archive: a mirror holding 1.0.0 will not fetch a different 1.0.0.
        apt_ly repo add -force-replace "$repo" "$f" >/dev/null \
            || { echo "FATAL: aptly refused $(basename "$f")" >&2; exit 1; }
    done

    # Architectures come from the packages. `all` belongs in every index rather than being
    # named, so it is dropped; if it were the only one the list would be empty.
    archs="$(printf '%s\n' "${found[@]}" | sed -E 's/.*_([a-z0-9]+)\.(deb|ddeb)$/\1/' \
        | sed '/^all$/d' | sort -u | paste -sd, -)"
    [ -n "$archs" ] || { echo "FATAL: $ep has only Architecture: all packages" >&2; exit 1; }

    snap="$ep-$STAMP"
    if apt_ly snapshot show "$snap" >/dev/null 2>&1; then
        # Snapshots are immutable, so reusing a stamp republishes the earlier contents.
        echo "    reusing existing snapshot $snap (promotion, not a new build)"
    else
        apt_ly snapshot create "$snap" from repo "$ep" >/dev/null
    fi

    line="$(apt_ly publish list 2>/dev/null | grep -F "filesystem:${ep}:./${SUITE} " || true)"
    existing="$(printf '%s' "$line" | sed -nE 's/.*\[([^]]*)\].*/\1/p' | norm)"
    # publish switch keeps the publication's architecture list, so a new architecture yields a
    # tree with no index for it.
    if [ -n "$existing" ] && [ "$existing" != "$(printf '%s' "$archs" | norm)" ]; then
        echo "    architectures changed ($existing -> $archs), republishing"
        apt_ly publish drop "$SUITE" "filesystem:${ep}:" >/dev/null
        line=""
    fi

    if [ -n "$line" ]; then
        apt_ly publish switch -gpg-key="$KEYID" -batch "$SUITE" "filesystem:${ep}:" "$snap" >/dev/null
        echo "    switched $SUITE -> $snap"
    else
        apt_ly publish snapshot -gpg-key="$KEYID" -batch -architectures="$archs" \
            -distribution="$SUITE" -component=main "$snap" "filesystem:${ep}:" >/dev/null
        echo "    published noble-nightly -> $snap [$archs]"
    fi
done

echo
echo "=============================================================="
echo " archive roots"
echo "=============================================================="
find "$DIST" -name InRelease | sort | sed "s|$DIST|  |"
echo
echo "The private roots are served behind the gateway; public needs no identity."
