#!/usr/bin/env python3
"""Check that a pull request is internally consistent about what it releases.

Three things have to agree, and the check runs in both directions because either half alone is a
silent failure:

  * a version bumped without a `release:` title ships a new version nobody reviewed as a release;
  * a `release:` title with no bump ships nothing, and the tag that follows names the old version;
  * a bump without a matching CHANGELOG section produces a .deb whose Debian changelog reads
    "Autogenerated, no changelog for this version found": bloom substitutes rather than failing.

Versions are per package and independent, so every check below is per package. A PR may release
several at once, or none.

Usage:  check_release_pr.py --base origin/main [--head HEAD] [--title "release: ..."]
Exit 0 if consistent, 1 if not.
"""
import argparse, re, subprocess, sys, xml.etree.ElementTree as ET
from pathlib import Path

RELEASE_TITLE = re.compile(r'^release(\([^)]*\))?!?:\s*\S', re.I)
# REP-132, and the exact shape catkin_pkg parses: X.Y.Z, one space, a date in parentheses.
SECTION = re.compile(r'^(\d+\.\d+\.\d+) \((.+)\)$', re.M)


def git(*args, allow_fail=False):
    r = subprocess.run(['git', *args], capture_output=True, text=True)
    if r.returncode and not allow_fail:
        raise SystemExit(f'git {" ".join(args)}: {r.stderr.strip()}')
    return r.stdout


def version_at(ref, path):
    """The <version> of a package.xml at a ref, or None if it did not exist there."""
    blob = git('show', f'{ref}:{path}', allow_fail=True)
    if not blob.strip():
        return None
    try:
        return (ET.fromstring(blob).findtext('version') or '').strip() or None
    except ET.ParseError:
        return None


def as_tuple(v):
    try:
        return tuple(int(p) for p in v.split('.'))
    except (ValueError, AttributeError):
        return None


def changelog_versions(ref, path):
    """Version headings present in a CHANGELOG.rst at a ref."""
    blob = git('show', f'{ref}:{path}', allow_fail=True)
    return {m.group(1) for m in SECTION.finditer(blob)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--base', required=True, help='what the PR merges into, e.g. origin/main')
    ap.add_argument('--head', default='HEAD')
    ap.add_argument('--title', default='', help='the pull request title')
    args = ap.parse_args()

    merge_base = git('merge-base', args.base, args.head).strip() or args.base
    touched = [p for p in git('diff', '--name-only', f'{merge_base}..{args.head}').split() if p]

    # Every package the PR touches at all, so a changelog edited without a bump is still seen.
    packages = {}
    for f in touched:
        parts = Path(f).parts
        for i in range(len(parts)):
            candidate = str(Path(*parts[:i + 1]) / 'package.xml')
            if candidate in touched or Path(candidate).exists():
                packages[str(Path(candidate).parent)] = candidate
                break

    problems, released = [], []
    for pkg_dir, pkg_xml in sorted(packages.items()):
        old = version_at(merge_base, pkg_xml)
        new = version_at(args.head, pkg_xml)
        name = Path(pkg_dir).name or pkg_xml

        if new is None:
            continue                      # deleted, or not a package after all
        if old == new:
            continue                      # untouched version: ordinary work, nothing to check

        released.append((name, old, new))

        if old is not None:
            o, n = as_tuple(old), as_tuple(new)
            if o and n and n <= o:
                problems.append(f'{name}: version went from {old} to {new}, which is not forward')

        changelog = str(Path(pkg_dir) / 'CHANGELOG.rst')
        if changelog not in touched and not Path(changelog).exists():
            problems.append(f'{name}: bumped to {new} with no CHANGELOG.rst')
            continue
        if new not in changelog_versions(args.head, changelog):
            problems.append(
                f'{name}: bumped to {new} but CHANGELOG.rst has no "{new} (YYYY-MM-DD)" section. '
                f'A release still under "Forthcoming" produces a .deb with no release notes, and '
                f'bloom substitutes a placeholder rather than failing')

    is_release = bool(RELEASE_TITLE.match(args.title.strip()))

    # The inversion: neither half may be true alone.
    if released and not is_release:
        problems.append(
            'version bumped in ' + ', '.join(n for n, _, _ in released) +
            ' but the title is not "release: ...". A bump is a release whether or not it is '
            'labelled one, and the label is what tells the pipeline to tag and publish')
    if is_release and not released:
        problems.append(
            'titled "release: ..." but no package.xml version changed, so there is nothing to '
            'release and the tag would name a version that already shipped')

    for name, old, new in released:
        print(f'  release  {name}  {old or "(new)"} -> {new}')
    if not released:
        print('  no version changes' + (' (not a release PR)' if not is_release else ''))
    for p in problems:
        print(f'  PROBLEM  {p}')

    if problems:
        print(f'\n  {len(problems)} problem(s)')
        return 1
    print(f'\n  consistent: {len(released)} package(s) released' if released else '\n  consistent')
    return 0


if __name__ == '__main__':
    sys.exit(main())
